[package]
name = "mysql-find-and-replace"
version = "0.1.0"
authors = ["Daniel Mason"]

[dependencies]
clap = {version = "^2.27.0", features = ["yaml"]}
failure = "^0.1.1"
mysql = "^14.0.0"
r2d2 = "^0.8.0"
r2d2_mysql = "^9.0.0"
rayon = "^1.0.2"
