[package]
name = "mysql-find-and-replace"
version = "0.1.0"
authors = ["Daniel Mason"]

[dependencies]
clap = {version = "^2.27.0", features = ["yaml"]}
diesel = { version = "^1.3", features = ["mysql"] }
failure = "^0.1.1"
mysql = "^14.0.0"
